### ISSUE TITLE
ModuleNotFoundError: No module named 'oauth2client'

### ISSUE THREAD

**Issue by jakupmichaelsen** [Hanse00/LecToCal#20]
I've just installed LecToCal using pip, but when trying to run `lectocal.gauth`, I get this error message:

`ModuleNotFoundError: No module named 'oauth2client'`

**Comment by Hanse00** [comment]
It looks like the oauth2client library has been deprecated in favor of google-auth: https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html

I'll have to implement the auth functionality using this new library, until then the oauth2client can manually be installed with `pip install oauth2client`.

**Comment by jakupmichaelsen** [comment]
Thank you!  :)

**Comment by Hanse00** [comment]
I've pushed a new version `1.2.1` which will explicitly require oauth2client from pip, meaning you should no longer need to install it manually.
