### ISSUE TITLE
ascii encoding problems...

### ISSUE THREAD

**Issue by TermeHansen** [Hanse00/LecToCal#5]
File "/usr/local/bin/lectocal.run", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lectocal/run.py", line 60, in main
    arguments.weeks)
  File "/usr/local/lib/python2.7/dist-packages/lectocal/lectio.py", line 240, in get_schedule
    return _retreive_user_schedule(school_id, user_type, user_id, n_weeks)
  File "/usr/local/lib/python2.7/dist-packages/lectocal/lectio.py", line 224, in _retreive_user_schedule
    week)
  File "/usr/local/lib/python2.7/dist-packages/lectocal/lectio.py", line 205, in _retreive_week_schedule
    schedule = _parse_page_to_lessons(r.content)
  File "/usr/local/lib/python2.7/dist-packages/lectocal/lectio.py", line 199, in _parse_page_to_lessons
    lessons.append(_parse_element_to_lesson(element))
  File "/usr/local/lib/python2.7/dist-packages/lectocal/lectio.py", line 188, in _parse_element_to_lesson
    return lesson.Lesson(id, summary, status, start_time, end_time, location)
  File "/usr/local/lib/python2.7/dist-packages/lectocal/lesson.py", line 31, in __init__
    self.id = self._gen_id()
  File "/usr/local/lib/python2.7/dist-packages/lectocal/lesson.py", line 67, in _gen_id
    str(self.start) + str(self.end) + \
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 3: ordinal not in range(128)

Jeg vil prøve at debugge det, men jeg skal lige ind i din kode, så hvis du ser det inden jeg får fundet og løst problemet vil det være fint :)

**Comment by Sobuno** [comment]
Har du et eksempel på et skema som forårsager dette? Så er det lidt lettere at prøve at debugge

**Comment by Hanse00** [comment]
Problemer her er at du bruger Python 2.x og ikke 3.x

I python 2 er string encoded med ASCII, altså kan det kun holde bogstaverne A - Z. Det ser ud som om dit skema indholder tegnet \xe5 som er et å, derfor kan det ikke konverteres til et ASCII tegn.

I python 3 behandles strings med unicode, hvor det ikke vil være et problem at konvertere til et bogstav, da å jo findes.

Prøv at køre programmet med python 3, og se om det ikke virker.

**Comment by TermeHansen** [comment]
Well jeg er enig i at det så er et python2 issue (som så kan fikses, så koden bliver python2 og 3 generisk), men så bør lectocal jo ikke ligge til at blive installeret med pip men med pip3 kun (som iøvrigt fejler her på debian jessie...
Downloading/unpacking lectocal
  Could not find a version that satisfies the requirement lectocal (from versions: 1.0.0a1, 1.0.0a3, 1.0.0a2, 1.0.0a1, 1.0.0a2, 1.0.0a3)
Cleaning up...
No distributions matching the version for lectocal
Storing debug log for failure in /root/.pip/pip.log
og den pip.log er tom....

**Comment by Hanse00** [comment]
I første omgang vil jeg være svar skyldig for hvordan det helt præcist hænger sammen. Det er lang tid siden jeg har arbejdet på det her projekt, men jeg mener [https://stackoverflow.com/a/10763461](https://stackoverflow.com/a/10763461) er metoden jeg selv brugte.

Jeg har helt sikkert med success brugt pip kommandoen direkte med python 3.

Men hvis det ikke virker, kan du jo altid downloade koden, og køre den direkte fra din kommando prompt.

**Comment by Hanse00** [comment]
Du skal iøvrigt være velkommen til selv at gøre koden python 2 venlig, eller ændre dokumentationen i [readme filen](https://github.com/Hanse00/LecToCal/blob/master/README.rst) så andre ikke får det samme problem i fremtiden 😃
