### ISSUE TITLE
lectocal.lectio.UserDoesNotExistError

### ISSUE THREAD

**Issue by tackleize** [Hanse00/LecToCal#8]
Hey!
Jeg får en errortekst, der ser sådan her ud:
File "/Library/Frameworks/Python.framework/Versions/3.6/bin/lectocal.run", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lectocal/run.py", line 60, in main
    arguments.weeks)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lectocal/lectio.py", line 239, in get_schedule
    school_id, user_type, user_id))
lectocal.lectio.UserDoesNotExistError: Couldn't find user - school: 40, type: student, id: 14736916388 - in Lectio.

Men jeg har eftertjekket, og al indtastet informationen burde være rigtig

**Comment by tackleize** [comment]
Fejlen sker på en MacBook Pro med macOS High Sierra v. 10.13.4

**Comment by Sobuno** [comment]
Det ser ud til at virke fint her:
![image](https://user-images.githubusercontent.com/3593183/38929369-5400b8aa-430c-11e8-9fd4-c94e4cf848e8.png)

Jeg har brugt følgende kommando
`(/usr/local/bin/lectocal.run 40 student 14736916388 --weeks 10 --calendar LectioSkema3 --credentials /home/pi/storage.json)`

Hvilken kommando bruger du?

**Comment by tackleize** [comment]
Jeg bruger lectocal.run 40 student 14736916388
Men selv med specificeringen af uger og kalendernavn giver den samme resultat :-/

**Comment by Sobuno** [comment]
Sidder du bag en proxy eller firewall som måske kan finde på at blokere dig? LecToCal forsøger specifikt at tjekke om brugeren eksistere ved at anvende denne URL: https://www.lectio.dk/lectio/40/SkemaNy.aspx?type=elev&elevid=14736916388&week=

Du kan evt. prøve at ændre funktionen _user_exists i lectio.py fra dette
`def _user_exists(school_id, user_type, user_id):
    r = _get_user_page(school_id, user_type, user_id)
    return r.status_code == requests.codes.ok
`
til dette
`def _user_exists(school_id, user_type, user_id):
    r = _get_user_page(school_id, user_type, user_id)
    print(r.status_code)
    return r.status_code == requests.codes.ok
`

Så burde den skrive HTTP status-koden ud også.

**Comment by tackleize** [comment]
Jeg ændrede funktionen og prøvede med min telefon som wi-fi hotspot i stedet. Desværre ledte det til præcis samme error

**Comment by Sobuno** [comment]
Ok, hvilken HTTP status-kode skrev den ud?

**Comment by Hanse00** [comment]
Jeg er ikke selv paa en computer pt. hvor jeg kan teste koden, men jeg har kopieret URLen i min browser, og indsat dinne vaerdier. Altsaa https://www.lectio.dk/lectio/40/SkemaNy.aspx?type=elev&elevid=14736916388&week=

Jeg faar umiddelbart i Chrome en 200 OK status kode, og siden loader for mig.
Faar du samme resultat? Loader siden for dig i en web browser uden at videresende dig til en anden side, saa som en wifi indlogningside?

Som @Sobuno forslog, hvad er resultatet af print(r.status_code)?

**Comment by tackleize** [comment]
Siden indlæser fint uden videresendelse
Selvom jeg har indsat linjen 

> print(r.status_code)

gør det ingen forskel på error-beskeden. 
Med andre ord, r.status_code bliver ikke printet.

**Comment by Sobuno** [comment]
Kører du seneste udgave herinde fra? Status code 301 betyder "Moved permanently" - Den ser vi hvis LecToCal stadig forsøger at ramme http i stedet for https.

Jeg ved ikke om de ændringer er blevet smidt i en package, men det kan @Hanse00 sikkert svare på.

**Comment by tackleize** [comment]
Jeg hentede den med pip kommandoen `pip install lectocal`

**Comment by Sobuno** [comment]
Ok, det tyder på, at de seneste ændringer ikke er blevet pakket - Jeg har desværre ikke rettigheder til at gøre dette, det er kun @Hanse00 som er maintainer på PyPi (https://pypi.org/project/lectocal/)

**Comment by tackleize** [comment]
Hmm.. Ærgerligt. :-/
Kan du hjælpe mig med at installere den nyeste version manuelt?

**Comment by Hanse00** [comment]
Jeg er i gang med at sætte tingene op så jeg kan skubbe en ny pakke, det er lidt tid siden jeg har arbejdet med Python uden for arbejdet.

Giver en opdatering når det er gjort.

**Comment by Hanse00** [comment]
Jeg har skubbet en ny version til pypi, og har selv tested at jeg kan synkronisere din lectio kalender.

Kan du vensligts checke om problemet er løst, efter at du opdatere din pakke @tackleize?

**Comment by tackleize** [comment]
Yes! Det fixede det!
Tusind tak for al hjælpen, @Hanse00 og @Sobuno ! I har været meget tålmodige!
Havde ikke mulighed for at tjekke før i dag, men nu virker alt præcis, som det bør. 😀
